dr_streamlit/predictor.py
When submitting a prediction, the real-time API returns a json and the batch API returns a csv. If the model only has a couple (eg 4) features but you requested many (eg 8) prediction explanations then you might end up with a situation where you don't get all 8 prediction explanations. In this case the single prediction API will send back a JSON with the explanations list with less than 8 entries -- BUT the batch prediction CSV will have empty columns. 
In order to parse these CSVs to have parity with the real-time API we need to filter out these null values.
=> [NCA-1182] Fix batch predictions breaking when the returned prediction had null values 

dr_streamlit/predictor.py, streamlit_app.py
Changed the assignment of prediction values for binary classification projects to look for the project's positive class rather than 0/1. 
Batch predictions only assign the positive class prediction, but this is usually what users will want anyway. Negative class predictions can be calculated with something like `1.0 - positive_class_prediction`.
=> Assign binary classification preds for pos class

Dockerfile
To make our docker image more friendly with running in the custom-apps infra, we must override the http port setting using an env var so this way the custom app infra can override it when it is running there (command line flags cannot be overridden).
Also make some minor tweaks to the image to improve layer caching and also add more build-time arguments so it is also possible to bake certain values into the image (which is currently required in the custom-apps infrastructure).
=> Fix the way we specify the port in our Docker image

drapps/helpers/execution_environments_functions.py, drapps/ls.py, setup.py, tests/cli/test_ls.py
Added `ls` command
```
Usage: ls [OPTIONS] {apps|envs}
Provide list of custom applications or execution environments.
Options:
-t, --token TEXT     Pubic API access token.
-E, --endpoint TEXT  Data Robot Public API endpoint.
--id-only            Output only ids
--help               Show this message and exit.
```
=> [APPLS-1798] Added command for getting applications and enviroments lists

drapps/helpers/custom_apps_functions.py, drapps/helpers/wrappers.py, drapps/logs.py, drapps/ls.py, drapps/terminate.py, tests/cli/test_logs.py, tests/cli/test_ls.py, tests/cli/test_terminate.py
Added terminate command.
```
Usage: drapps terminate [OPTIONS] APPLICATION_ID_OR_NAME...
Provide logs for custom application.
Options:
-t, --token TEXT     Pubic API access token.
-E, --endpoint TEXT  Data Robot Public API endpoint.
--help               Show this message and exit.
```
It accept applications names and IDs:
```
drapps terminate app_name_1 app_name_2
```
And piping is also possible:
```
drapps ls --id-only apps | drapps terminate
```
=> [APPLS-1799] Added terminate command

README.md, bin/drapps, drapps/__main__.py
I went through the flow of installing Python on a Windows laptop, and uploading an app. I ran into issues registering the drapps python code, and decided the most portable experience was to just make it a module. I also had trouble with the named execution environment, but using an ID worked, so I wanted to note that.
=> [APPLS-1946] Allow drapps to work via a module command (python -m drapps ... )

examples/prediction-demo/dr_streamlit/create_prediction.py
- Used the code provided in the JIRA ticket by Olga.
- I've assumed the datatype to be `Text` instead of `Numeric`.
- Tried running the predictions locally and verified that they work as expected for `association_id` that consists of both letters and just numbers.
=> [APP-2623] Automatically add `association_id` as a field to Streamlit Apps

README.md, drapps/__main__.py, drapps/create.py, drapps/env.py, setup.cfg, tests/cli/test_env.py
With the launch of 10.0, some customers using on-prem or ST SAAS DataRobot will need to have a base execution environment. Other customers may want to make execution environments which have different base images (eg use python 3.12) or different versions (eg users making a flask app who don't want streamlit) 
This PR consolidates a few commands together to make creating an execution environment as easy as a few commands.
=> [APP-2754] Add create_env command to drapps CLI

examples/prediction-demo/dr_streamlit/predictor.py, examples/prediction-demo/requirements.txt
- Here's the JIRA Ticket: [APP-2756](https://datarobot.atlassian.net/browse/APP-2756)
- The code checks if the prediction environment is `serverless` before making the prediction request.
- Also bumped up the `datarobot` python library version from `3.0.2` to `3.4.0`.
- Verified that the predictions work successfully for both `Serverless` and `Staging` environments.
[APP-2756]: https://datarobot.atlassian.net/browse/APP-2756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [APP-2756] Fix bug for the example demo for DR Serverless prediction environments

setup.cfg
Some consumers of the dr-apps CLI use the 10.0 version of DR (such as On Prem or Single Tenant users), and some users are on 10.1 because they are cloud users. 
Having breaking changes has already caused some pain since `customApplicationSources` was introduced as part of  10.1 and deprecated `customApplicationImages` which is part of 10.0, so the 10.1 CLI is not compatible with 10.0 since the CLI references an API which does not exist. Other libraries, like [python's Kubernetes library](https://github.com/kubernetes-client/python?tab=readme-ov-file#homogenizing-the-kubernetes-python-client-versions) follow this pattern, so I think it makes sense to do this too. 
As the custom apps product matures, it may be confusing if we make more changes like this. We hope that this means:
1. On-Prem …
=> [APP-2810] Use standardized versioning for dr-apps

drapps/helpers/exceptions.py, drapps/helpers/handle_dr_response.py
- JIRA Ticket: [APP-2837](https://datarobot.atlassian.net/browse/APP-2837)
- The `errors` argument is of type `Dict`. It can have multiple key-value pairs where the keys are the type of the error.
- Here's an example:
- `drapps.helpers.exceptions.ClientResponseError: 422, message=Invalid field data, url=https://staging.datarobot.com/api/v2/customApplicationSources/667c6e24a92a7259bce1c64c/versions/667c6e24cdfbac19fc7cfeb0/, errors={'filePaths': 'Do not use metadata.yaml file. We do not support runtime parameters.'}`
[APP-2837]: https://datarobot.atlassian.net/browse/APP-2837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [APP-2837] Add `errors` when available to the error message given by `ClientResponseError`

drapps/helpers/custom_apps_functions.py, drapps/publish.py, setup.cfg, tests/cli/test_publish.py
With the new Custom Apps publishing functionality, the process of publishing an app may take a few (~3) minutes. Having the process be an async thing where you kick off a job, and wait for the job to be ready is a bad user experience because there's no way to know when your published app is ready, or making progress, or errored. 
This PR is coupled with a PR on our internal repo to add a URL to the publication (See that for more info please!)
=> [APP 2834] Add CLI flag for monitoring publication status

drapps/create.py, setup.cfg, tests/cli/test_create.py
=> [APP-2916] use v{num} instead of script_generated_{num}

drapps/helpers/custom_apps_functions.py, setup.cfg
The publication flow is:
Build new app --> Start new app --> Stop old app
and so the check was (erroneously) to wait for the old app to be fully stopped. This only makes sense if the app's initial state is `running`. If the app that's set to be published to starts as `paused` then the CLI will think the app has already published the new version, when in fact it has not.
=> [APP-2973] Fix check for publishing when app starts in a stopped state

drapps/helpers/custom_apps_functions.py, drapps/publish.py, setup.cfg, tests/cli/test_publish.py
It doesn't make sense for the DataRobot application to use the `app.status` attribute and the CLI to use the `/status/` API
We should remove this API before making things GA so we don't have an unused API
=> [APP-3079] [App 3079] rely on `running` from status API, and remove usage of /status/ API

README.md
The README mentions streamlit 1.17.0 for the custom envirionment, it is too old for the demo application that use cache_data.
Update example dockerfile to the latest from dropin envs
=> [APP-3113] Update readme dockerfile example

drapps/create.py, drapps/helpers/custom_app_sources_functions.py, setup.cfg, tests/cli/test_create.py
This provides functionality to add:
1. The number of specified replicas
2. The CPU size of the running container
Via a command like:
```
drapps create EXAMPLE_APP --path examples/myExample/ --base-env MyAwesomeEnv --replicas 2 --cpu-size large
```
> [!TIP]
> The sizes correspond to:
> | name | CPU  | RAM |
> | ----| -------------- | ------|
> | nano| 1 CPU | 128MB |
> | micro | 1 CPU | 256MB |
> | small | 1 CPU | 512MB | 
> | medium | 1 CPU | 1GB |
> | large | 2 CPU | 1.5GB |
> | xlarge | 2 CPU | 2GB |
> | 2xlarge | 2 CPU | 3GB |
=> [APP-3259] Add logic for creating apps w/ custom num instances or resources

drapps/env.py, setup.cfg
The dockerfile path for `drapps create-env` is set as a not required argument, BUT in the type hinting it's not listed as an `Optional[Path]`:
https://github.com/datarobot/dr-apps/blob/b0615531ea753cd2bc01dbc6eac9f70449734be7/drapps/env.py#L45
In the upload logic there is no None check. :
https://github.com/datarobot/dr-apps/blob/b0615531ea753cd2bc01dbc6eac9f70449734be7/drapps/create.py#L291-L292
so the code as-it-is assumes there's never a None supplied.
Furthermore, this logic cannot work fully with no docker context, so it doesn't make sense to support None checking.
=> [APP-3369] Make the dockerfile zip path required

drapps/__main__.py, drapps/externalshare.py, drapps/ls.py, setup.cfg, tests/cli/test_externalshare.py, tests/cli/test_ls.py
The external sharing (email sharing) doesn't have any implementation in the datarobot apps CLI, so CLI only users have to either hand-roll requests or go to the UI to manage external sharing. 
This PR adds functionality in tandem with DOC-7233 to allow us to:
0. Toggle external sharing on/off
1. Add external users
2. Remove external users
3. View the external sharing / external sharing users. 
Example Usages:
```
Enable external sharing for an app:
> drapps external-share 6728fce3a2ad2d97d14b04aa --set-external-sharing True
Enable external sharing (by ID) for my account
> drapps external-share 6728fce3a2ad2d97d14b04aa --add-external-user ben.cutler@datarobot.com
Enable external sharing (by name) for my account
> drapps external-share MyAwesomeApp --add-external-user …
```
=> [APP-3485] Allow apps CLI to manage external sharing

README.md, examples/prediction-demo/.streamlit/config.toml, examples/prediction-demo/dr-logo.svg, examples/prediction-demo/dr_streamlit/caches.py, examples/prediction-demo/dr_streamlit/create_prediction.py, examples/prediction-demo/dr_streamlit/feature_impact.py, examples/prediction-demo/dr_streamlit/predictor.py, examples/prediction-demo/dr_streamlit/select_box.py, examples/prediction-demo/dr_streamlit/wordcloud.py, examples/prediction-demo/dr_streamlit/wrappers.py, examples/prediction-demo/requirements.txt, examples/prediction-demo/start-app.sh, examples/prediction-demo/streamlit_app.py, setup.py
This PR fixes a series of issues:
- Replace the outdated/unmaintained `streamlit-wordcloud` lib, using [wordcloud](https://pypi.org/project/wordcloud/) instead
- Update dependencies for example apps (Lets us get rid of the numpy 1.20 dep)
- Use latest DR logo in example app
- Fix cache issue with deployment vs deployment_id
- Remove mentions of the old Experimental execution env in favor of `[DataRobot] Python 3.12 Applications Base`
=> [APP-2887] Replace streamlit-wordcloud and bump all dependencies

LICENSE
I want to use the same license as the streamlit SAL Package:
https://github.com/datarobot-oss/streamlit-sal/blob/main/LICENSE
Because:
1. I want anyone to be able to make changes (eg if customer X wants to fork it and add some features to the CLI they should be free to) 
2. I want anyone to be able to re-host it with those changes (If customer X who forked it with changes wants to store it in their proprietary hosting service, that's fine)
=> Add a license to the Apps CLI

drapps/create.py, drapps/helpers/app_projects_functions.py, setup.cfg, tests/cli/test_create.py, tests/conftest.py
The current flow of uploading files causes everything in the directory to be uploaded.  This means all sorts of stuff can be uploaded: your `.git` folder which is full of junk, the `.env` with your credentials, the `node_modules` folder.  This sees like a problem. 
Rather than hand-roll my own syntax for reading files, it makes more sense to lean on the formatting provided by a well known spec such as .gitignore, and re-use that syntax.
=> [APP-3616] Add dr_apps_ignore file support

drapps/create.py, setup.cfg
In the off-chance that we are having issues with the execution environment setup, we should make sure we don't wait forever for an env version to be created.
=> [CIDG-1192] Don't wait forever for an execution env to be created

.harness/on_pr_update/pipeline.yaml, Makefile, setup.py
This PR does two things:
1. It adds needed dependencies to the drapps CLI package which were needed (in this case, pyYAML + pathspec). These likely slipped through the cracks because transitive dependencies in our test package worked. 
2. It adds a harness CI test to make sure we can run `drapps` and get a successful exit code. That way, if we have a missing dependency in the future, we'll know.
=> [APP-3162] Fix drapps base requirements missing needed packages

drapps/create.py, drapps/helpers/custom_app_sources_functions.py, tests/cli/test_create.py
We have added support for making apps run on `/`. Currently they run on `/apps/id/<path>` , which corresponds to `/apps/id/<path>`, and need to have an exposed route on `/apps/id` for the K8s healthcheck API.
This PR adds that functionality to the apps CLI
=> [APP-3651] Add apps CLI suport to building apps which run on `/`

drapps/create.py, drapps/helpers/custom_app_sources_functions.py, tests/cli/test_create.py
Basically, when we use the latest version of the apps CLI and we send requests to old versions of DataRobot (eg an old 10.2 cluster) we get errors that `serviceWebRequestsOnRootPath` or `sessionAffinity` are not known resource keys as they are sent as `False`. 
While we *do* have a 10.2 branch, it's very likely that customers  are not going to point to our 10.2 branch, and instead `pip` install the latest, so we should clean up this point of friction before it causes an issue. It's also much more likely to cause issues for DataRobot developers who want to test against 10.2 to use the latest apps CLI.
=> [-] Replace `False` with `None` to make new versions of apps CLI work with 10.2.x

drapps/create.py, drapps/helpers/execution_environments_functions.py, setup.cfg, tests/cli/test_env.py
An error saying:
```
Image Build Failed
```
Doesn't mean anything. Customers don't know what `Image Build Failed` means, and there's no way to know if the Image Build Failed log means the image build for the app, the intermediate build for the app (in the case of a build-app.sh, or requirements.txt) , or the execution environment version.  I want to solve two problems with this:
1. We should make this error message understandable. Customers don't know what the `Image Build` really means, but they probably know what it means when their image build failed.
2. Getting logs, is *usually* a good way to get started at figuring out what's wrong.  The Apps team uses the apps CLI for testing environments, and this error will be useful to *us* so we imagine it's useful generally.
=> [-] Supply a better error message for Execution Environment Version failing to build
